version: "3"
services:
  redis:
    image: redis

  db:
    image: postgres:9.4
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"

  vote:
    image: voting-app
    ports:
      - 5000:80
    links:
      - redis


  worker:
    image: worker-app
    links:
      - db
      - redis

  result:
    image: result-app
    ports:
      - 5001:80
    links:
      - db  
